scenario card arrows added
DLR-SC/ESID pull request #149
Opened 2022-07-27 09:49 UTC by PawanKaur

issue #147 

There are problems of showing the arrows with the Recovered compartment.

2022-08-16 11:45 UTC, NXXR requested changes
There are a few things that need to be addressed before merging:
- [x] run formatting (`npm run format`) to make sure the code is properly formatted and passes the DevOps pipeline
- [x] fix the lince height of the compartments (the changes result in scenario card compartment entries with more space between rows which lead to a mismatch between the header rows and the compartment rows:  
    ![grafik](https://user-images.githubusercontent.com/25636783/184871480-ddc21826-e954-4066-b281-acde22a78bd6.png)
- [ ] address the changes suggested/mentioned by Martin in the last Sprint meeting (changing the "positive" direction/color of the arrows & adding a neutral option, changeing how incremental values are handled)

2022-08-26 13:23 UTC, PawanKaur commented
As discussed, to change condition of grey arrow. It should show when the change is not significant or less than 1%

2022-09-12 10:42 UTC, PawanKaur commented
- Stagnation rule applied, grey arrow will show up if the change is more than 3%. 
- Arrows also showing up on the basis of compartment value for those cases where RKI values are 0.

2022-09-30 14:44 UTC, NXXR requested changes

2022-09-30 14:44 UTC, NXXR commented on frontend/src/components/Sidebar/DistrictMap.tsx
> +import HomeIcon from '@mui/icons-material/Home';
These changes have nothing to do with this PR.
```suggestion
```

2022-09-30 14:44 UTC, NXXR commented on frontend/src/components/Sidebar/DistrictMap.tsx
> +  const selectedDistrict = useAppSelector((state) => state.dataSelection.district);
These changes have nothing to do with this PR.
```suggestion
  //const selectedDistrict = useAppSelector((state) => state.dataSelection.district);
```

2022-09-30 14:44 UTC, NXXR commented on frontend/src/components/Sidebar/DistrictMap.tsx
> +  }, [selectedDistrict]);
These changes have nothing to do with this PR.
```suggestion

```

2022-09-30 14:44 UTC, NXXR commented on frontend/src/components/Sidebar/DistrictMap.tsx
> +          />
These changes have nothing to do with this PR.
```suggestion
```

2022-10-25 10:17 UTC, NXXR approved these changes

2022-10-26 11:01 UTC, merged