Feature/map reset
DLR-SC/ESID pull request #172
Opened 2022-09-14 09:02 UTC by PawanKaur

For issue 98 and 92
1) Reset the values to Germany: A reset icon is added at the search bar
2) Reset zoom level. A home icon is added to the map that resets the zoom level to the default. It also changes the value to Germany wide. Till the time highlight district is not activated on the map, this functionality is needed else, its difficult to track the selected district on the map view.

2022-09-30 14:34 UTC, NXXR requested changes
some changes from other PRs mixed in again.
Also, the zoom out button also selects germany again, I'm confused on what we decided on for the interaction.

2022-09-30 14:34 UTC, NXXR commented on frontend/src/components/ScenarioCard.tsx
> +import ArrowRightIcon from '@mui/icons-material/ArrowRight';
These are changes from PR #149 right?
```suggestion
```

2022-09-30 14:34 UTC, NXXR commented on frontend/src/components/ScenarioCard.tsx
> +
These are changes from PR #149 right?
```suggestion
```

2022-09-30 14:34 UTC, NXXR commented on frontend/src/components/ScenarioCard.tsx
> +                ></ArrowRightIcon>
These are changes from PR #149 right?
```suggestion
```

2022-09-30 14:34 UTC, NXXR commented on frontend/src/components/Sidebar/DistrictMap.tsx
> +        maxZoomLevel: 5,
Is there a reason for the changed zoom level?

2022-09-30 14:34 UTC, NXXR commented on frontend/src/components/Sidebar/DistrictMap.tsx
> +            }
This is also part of a different PR right?
```suggestion
            max={legend.isNormalized ? aggregatedMax : legend.steps[legend.steps.length - 1].value}
```

2022-09-30 14:34 UTC, NXXR commented on frontend/src/components/Sidebar/DistrictMap.tsx
> +              dispatch(selectDistrict({ags: '00000', name: t('germany'), type: ''}));
why are we chanign the selected district too on the zoom out button?
To me it seems more intuitive if the Zoom out button just zooms and pans the map back into its default position.

Or did we have another reason for this?
```suggestion
```

2022-10-25 09:27 UTC, NXXR requested changes
The size of the gemany icon/button does not match the size of the other two buttons.
or is that just with my build?

2022-12-16 17:01 UTC, PawanKaur commented
> The size of the gemany icon/button does not match the size of the other two buttons. or is that just with my build?

I am not sure how it looks at your end, but at my side, it does not look much bigger or different.

2022-12-16 17:02 UTC, PawanKaur commented
> Also make sure to pull the newest changes of the develop branch and resolve any issues blocking the merge :)
Done

2023-01-30 13:11 UTC, NXXR commented
> > The size of the gemany icon/button does not match the size of the other two buttons. or is that just with my build?
> 
> I am not sure how it looks at your end, but at my side, it does not look much bigger or different.

![grafik](https://user-images.githubusercontent.com/25636783/215485824-100a05bf-3588-453a-b889-928ca050b856.png)

This is how it looks on my end.
I was talking with Jonas to check if it was a problem on my end.

I think we should try to get the button into the map controls container so it's closer and in the same style as the zoom buttons.

This way it doesn't look out of place between the zoom controls and the heat legend buttons.

If we can't get it into the zoom controls we should try to at least match the style.

2023-02-08 09:10 UTC, NXXR requested changes
see comment above.

2024-03-08 12:11 UTC, closed without merging