Upgrade line chart to amCharts 5
DLR-SC/ESID pull request #277
Opened 2023-07-04 17:11 UTC by NXXR

### Description
This PR updates the line chart to use amCharts 5.

#### Related Issues
- #68 
- #93 

### Performance & Quality

### Checklist

**I, the author of this PR checked the following requirements for good software quality:**

- [x] The code is properly formatted (I ran the formatter)
- [x] The code is written with our software quality standards (I ran the linter)
- [x] The code is written using our code style
- [x] Extensive in source documentation has been added
- [x] ~~Unit and/or integration tests have been added~~
- [x] All texts have been internationalized with at least the following languages:
  - [x] English
  - [x] German
- [x] I tried addressing all new accessibility problems displayed in the console and documented if they can't be fixed
- [x] I attached performance measurements to prevent performance degradation
- [x] I added the changes to the next release section of the [changelog](../frontend/docs/changelog/changelog-en.md)

**I, the reviewer checked the following things:**

- [ ] I ran the software once and tried all new and related functionality to this PR
- [ ] I looked at all new and changed lines of code and commented on possible problems
- [ ] I read the added documentation and checked if it is understandable and clear
- [ ] I checked the added tests for completeness
- [ ] I checked the internationalized strings for spelling errors
- [ ] I checked the performance metrics for problems or unexplained degradation
- [ ] I checked that the changes are noted in the [changelog](../frontend/docs/changelog/changelog-en.md)

2023-07-05 15:05 UTC, JonasGilg requested changes

2023-07-05 15:05 UTC, JonasGilg commented on frontend/src/components/SimulationChart.tsx
> +      const Xrenderer = xAxis.get('renderer');
```suggestion
      const xRenderer = xAxis.get('renderer');
```

2023-07-05 15:05 UTC, JonasGilg commented on frontend/src/components/SimulationChart.tsx
> +      Xrenderer.ticks.template.setAll({
```suggestion
      xRenderer.ticks.template.setAll({
```

2023-07-06 07:41 UTC, JonasGilg commented
Can you make the date selection a single click again?

2023-07-06 12:45 UTC, NXXR commented
> Can you make the date selection a single click again?

sorry,
forgot yesterday.
is fixed now.

2023-07-06 12:51 UTC, JonasGilg submitted a review, later dismissed
Feels much better now. Sadly I discovered another issue. If you toggle a scenario or group filters the time selector goes missing :(

2023-07-06 13:02 UTC, NXXR commented
> Feels much better now. Sadly I discovered another issue. If you toggle a scenario or group filters the time selector goes missing :(

looking into it.
It seems to only happen when you activate/deactivate the first scenario or group filters, but not with the second scenario.
Can you confirm that?

2023-07-06 13:17 UTC, JonasGilg commented
> It seems to only happen when you activate/deactivate the first scenario or group filters, but not with the second scenario.
Can you confirm that?

Also happens with other scenarios/filters and when reloading the page.

2023-07-13 14:08 UTC, NXXR commented
guide dissapperaing (#252 ) should be fixed now

2023-07-24 13:41 UTC, JonasGilg requested changes

2023-07-24 13:41 UTC, JonasGilg commented on frontend/src/components/SimulationChart.tsx
> +      if (!rootRef.current || !chartRef.current) return;
```suggestion
      if (!rootRef.current || !chartRef.current) {
        return;
      }
```

2023-07-24 13:41 UTC, JonasGilg commented on frontend/src/components/SimulationChart.tsx
> +        rootRef.current && rootRef.current.dispose();
```suggestion
        chartRef.current?.dispose();
        rootRef.current?.dispose();
```

2023-07-24 13:41 UTC, JonasGilg commented on frontend/src/components/SimulationChart.tsx
> +      if (!rootRef.current || !chartRef.current) return;
```suggestion
      if (!rootRef.current || !chartRef.current) {
        return;
      }
```

2023-07-24 13:41 UTC, JonasGilg commented on frontend/src/components/SimulationChart.tsx
> +      if (!chartRef.current || !rootRef.current || !selectedDate) return;
```suggestion
      if (!chartRef.current || !rootRef.current || !selectedDate) {
        return;
      }
```

2023-07-24 13:56 UTC, JonasGilg approved these changes

2023-07-24 14:18 UTC, merged