Feature/case data card
DLR-SC/ESID pull request #287
Opened 2023-07-19 15:04 UTC by JonasGilg

### Description

Adds a new card for case data in black. Additionally the Map now also can show case data if the case data card is selected.

The selected compartment is now also highlighted in the cards.

A little bit of refactoring also made it into this PR.

#### Related Issues

Closes #262

### Design Decisions

### Performance & Quality

### Checklist

**I, the author of this PR checked the following requirements for good software quality:**

- [ ] The code is properly formatted (I ran the formatter)
- [ ] The code is written with our software quality standards (I ran the linter)
- [ ] The code is written using our code style
- [ ] Extensive in source documentation has been added
- [ ] Unit and/or integration tests have been added
- [ ] All texts have been internationalized with at least the following languages:
  - [ ] English
  - [ ] German
- [ ] I tried addressing all new accessibility problems displayed in the console and documented if they can't be fixed
- [ ] I attached performance measurements to prevent performance degradation
- [ ] I added the changes to the next release section of the [changelog](../frontend/docs/changelog/changelog-en.md)

**I, the reviewer checked the following things:**

- [ ] I ran the software once and tried all new and related functionality to this PR
- [ ] I looked at all new and changed lines of code and commented on possible problems
- [ ] I read the added documentation and checked if it is understandable and clear
- [ ] I checked the added tests for completeness
- [ ] I checked the internationalized strings for spelling errors
- [ ] I checked the performance metrics for problems or unexplained degradation
- [ ] I checked that the changes are noted in the [changelog](../frontend/docs/changelog/changelog-en.md)

2023-08-23 14:26 UTC, JonasGilg commented on frontend/src/components/Scenario/CaseDataCard.tsx
> +    }
```suggestion
    if (data || data.results.length > 0) {
      return data.results[0].compartments;
    }
```

2023-09-13 14:53 UTC, NXXR requested changes

2023-09-13 14:53 UTC, NXXR commented on frontend/src/components/Scenario/index.tsx
> +        >
```suggestion
        <Dialog
          id='manage-filters-dialog'
          maxWidth='lg'
          fullWidth={true}
          open={open}
          onClose={() => {
            if (groupEditorUnsavedChanges) {
              setCloseDialogOpen(true);
            } else {
              setOpen(false);
            }
          }}
        >
```

2023-09-13 14:53 UTC, NXXR commented on frontend/src/components/Scenario/CompartmentList.tsx
> +      >
```suggestion
      <Button
        id='toggle-expanded-compartments-button'
        variant='outlined'
        color='primary'
        sx={{
          margin: theme.spacing(3),
          marginTop: theme.spacing(4),
          marginBottom: 0,
          padding: theme.spacing(1),
        }}
        aria-label={t('scenario.more')}
        onClick={() => {
          dispatch(toggleCompartmentExpansion());
          if (
            compartments.findIndex((o) => {
              return o === selectedCompartment;
            }) > 4
          ) {
            if (compartments.length > 0) {
              dispatch(selectCompartment(compartments[0]));
            }
          }
        }}
      >
```

2023-09-13 14:53 UTC, NXXR commented on frontend/src/components/Scenario/CompartmentList.tsx
> +  const startDay = useAppSelector((state) => state.dataSelection.minDate);
Not entirely sure if this works properly.
Day needs to be adjusted.
```suggestion
  const startDay = useAppSelector((state) => {
    let date = new Date(state.dataSelection.minDate);
    // start day is the day before the first simulation result
    date = new Date(date.getDate() - 1);
    return `${date.toISOString()[0:9]}`
  });
```

2023-09-13 14:53 UTC, NXXR commented on frontend/src/components/Scenario/DataCardList.tsx
> +        // It seems, that the simulation data is only available from the second day forward.
```suggestion
        // The simulation data (results) are only available one day after the start day onward.
```

2023-09-13 14:53 UTC, NXXR commented on frontend/src/components/Scenario/DataCard.tsx
> +      >
```suggestion
      <Box
        id='scenario-card-container'
        sx={{
          position: 'relative',
          zIndex: 0,
          flexGrow: 0,
          flexShrink: 0,
          width: '200px',
          boxSizing: 'border-box',
          marginX: '2px',
          marginY: theme.spacing(2),
          marginBottom: 0,
        }}
        onMouseLeave={() => setHover(false)}
      >
```

2023-09-13 14:53 UTC, NXXR commented on frontend/src/components/Scenario/GroupFilterAppendage.tsx
> +    >
```suggestion
    <Box
      id={`scenario-card-${props.scenarioId}-group-filter-container`}
      sx={{
        display: 'flex',
        flexDirection: 'row',
        marginY: theme.spacing(2),
        marginLeft: '-3px',
        padding: '1px',
        height: 'min-content',
        border: `1px solid ${props.color}`,
        borderRadius: '3px',
        background: theme.palette.background.paper,
      }}
    >
```

2023-09-13 14:53 UTC, NXXR commented on frontend/src/components/Scenario/GroupFilterAppendage.tsx
> +      >
```suggestion
      <Button
        id={`scenario-card-${props.scenarioId}-group-filter-fold-toggle`}
        sx={{
          width: '26px',
          minWidth: '26px',
          borderRight: `1px solid ${theme.palette.divider}`,
        }}
        onClick={() => setFolded(!folded)}
      >
```

2023-09-13 15:34 UTC, NXXR approved these changes

2023-09-13 15:34 UTC, merged