Feature/parameter view
DLR-SC/ESID pull request #345
Opened 2024-03-15 15:47 UTC by JonasGilg

### Description

This PR changes the main content area. At the bottom the user can now choose between two tabs. One being the time series and the other is the new parameter view, which displays the infection parameters.

![image](https://github.com/DLR-SC/ESID/assets/9581540/a681a5b6-e420-4b32-b885-a8615821625e)
![image](https://github.com/DLR-SC/ESID/assets/9581540/6aca698d-6ff5-4c4c-8ee7-3d40d943078f)

#### Related Issues

Resolves #309

### Checklist

**I, the author of this PR checked the following requirements for good software quality:**

- [ ] The code is properly formatted (I ran the formatter)
- [ ] The code is written with our software quality standards (I ran the linter)
- [ ] The code is written using our code style
- [ ] Extensive in source documentation has been added
- [ ] Unit and/or integration tests have been added
- [ ] All texts have been internationalized with at least the following languages:
  - [ ] English
  - [ ] German
- [ ] I tried addressing all new accessibility problems displayed in the console and documented if they can't be fixed
- [ ] I attached performance measurements to prevent performance degradation
- [ ] I added the changes to the next release section of the [changelog](../frontend/docs/changelog/changelog-en.md)

**I, the reviewer checked the following things:**

- [ ] I ran the software once and tried all new and related functionality to this PR
- [ ] I looked at all new and changed lines of code and commented on possible problems
- [ ] I read the added documentation and checked if it is understandable and clear
- [ ] I checked the added tests for completeness
- [ ] I checked the internationalized strings for spelling errors
- [ ] I checked the performance metrics for problems or unexplained degradation
- [ ] I checked that the changes are noted in the [changelog](../frontend/docs/changelog/changelog-en.md)

2024-03-22 13:14 UTC, NXXR requested changes
Looks good.
just a few suggestions and open questions.

2024-04-04 08:40 UTC, JonasGilg commented on frontend/locales/de-backend.json5
> +    },
Yes, there is not symbol for this parameter. I cannot comment on the units of measurement, maybe this can be improved on in the future.

2024-04-04 08:40 UTC, JonasGilg commented on frontend/locales/de-backend.json5
I wouldn't do it now, but in a future PR.

2024-04-05 09:18 UTC, NXXR approved these changes

2024-04-05 09:20 UTC, merged