Feature/onboarding
DLR-SC/ESID pull request #377
Opened 2024-08-02 13:31 UTC by emilijadunoska

### Description

#### Related Issues

### Design Decisions

### Performance & Quality

### Checklist

**I, the author of this PR checked the following requirements for good software quality:**

- [ ] The code is properly formatted (I ran the formatter)
- [ ] The code is written with our software quality standards (I ran the linter)
- [ ] The code is written using our code style
- [ ] Extensive in source documentation has been added
- [ ] Unit and/or integration tests have been added
- [ ] All texts have been internationalized with at least the following languages:
  - [ ] English
  - [ ] German
- [ ] I tried addressing all new accessibility problems displayed in the console and documented if they can't be fixed
- [ ] I attached performance measurements to prevent performance degradation
- [ ] I added the changes to the next release section of the [changelog](../frontend/docs/changelog/changelog-en.md)

**I, the reviewer checked the following things:**

- [ ] I ran the software once and tried all new and related functionality to this PR
- [ ] I looked at all new and changed lines of code and commented on possible problems
- [ ] I read the added documentation and checked if it is understandable and clear
- [ ] I checked the added tests for completeness
- [ ] I checked the internationalized strings for spelling errors
- [ ] I checked the performance metrics for problems or unexplained degradation
- [ ] I checked that the changes are noted in the [changelog](../frontend/docs/changelog/changelog-en.md)

2024-09-02 14:48 UTC, JonasGilg requested changes
Looks very good. The code quality is very high.

Apart from the comments and suggestions I already made the only other change request would be to suggest, for you to write all comments with a capital letter at the start and if they form a sentence also with a period at the end.

2024-09-02 14:48 UTC, JonasGilg commented on frontend/.env.template
The code here shoudn't be removed.

2024-09-02 14:48 UTC, JonasGilg commented on frontend/docs/changelog/changelog-de.md
> +  - Willkommensmodal, das dem Benutzer beim ersten Besuch einen Überblick über die ESID anhand von Folien und Illustrationen zeigt
```suggestion
  - Willkommensmodal, das dem Benutzer beim ersten Besuch einen Überblick über ESID anhand von Folien und Illustrationen zeigt
```

2024-09-02 14:48 UTC, JonasGilg commented on frontend/src/components/OnboardingComponents/TourComponents/TourSteps.tsx
> +  /**the current step index of the tour, keeping state of this value is necessary for joyride controlled (interactive) tours */
```suggestion
  /** a flag to run or stop the tour */
  run: boolean;
  /** array of Step objects for the tour */
  steps: Step[];
  /** the current step index of the tour, keeping state of this value is necessary for joyride controlled (interactive) tours */
```

2024-09-02 14:48 UTC, JonasGilg commented on frontend/src/components/OnboardingComponents/WelcomeDialog/WelcomeDialog.tsx
> +              )
Can you move this to a function/callback?

2024-09-02 14:48 UTC, JonasGilg commented on frontend/src/components/OnboardingComponents/WelcomeDialog/WelcomeDialog.tsx
> +              )
Can you move this to a function/callback?

2024-09-04 09:26 UTC, emilijadunoska commented
> Looks very good. The code quality is very high.
> 
> Apart from the comments and suggestions I already made the only other change request would be to suggest, for you to write all comments with a capital letter at the start and if they form a sentence also with a period at the end.

Thank you for the positive feedback! I've addressed the comments and suggestions you made.

2024-09-06 08:06 UTC, JonasGilg approved these changes

2024-09-06 08:48 UTC, merged